name: application-restricted # Will have SERVICE_NAME- prepended to this
displayName: Personal Demographics Service - Application Restricted
description: Access the Personal Demographics Service with reduced permisions.
scopes:
  - access_mode:APPLICATION-RESTRICTED
environments:
  - prod
  - ref
attributes:
  - name: access
    value: public
  - name: ratelimit
    value: 15000pm # 250tps in 1s buckets
quota: 7800 # 130tps
quotaInterval: 1
quotaTimeUnit: minute
