name: Cleanup

on:
  pull_request:
    types:
      - closed

jobs:
  teardown:
    name: Teardown
    runs-on: ubuntu-latest
    steps:
      - name: Kickoff teardown pipeline
        run: |
          curl -X POST "https://vsrm.dev.azure.com/NHSD-APIM/API%20Platform/_apis/release/releases?api-version=5.0" \
               -u ${{ secrets.AZURE_DEVOPS_USER }}:${{ secrets.AZURE_DEVOPS_TOKEN }} \
               -H "Content-Type: application/json; charset=utf-8" \
               -d "{\"definitionId\": 24\, \"variables\": {\"TEARDOWN_BRANCH\": {\"value\": \"$GITHUB_REF\"}}}"
